README.md, core/resolver.go
This PR allows using `commit: latest` instead of manually providing a commit hash when using a git source, which allows builds to always pull the most recent commit from a specified branch.
Closes #3 .
=> Allow using `latest` as git commit

core/resolver.go, core/resolver_test.go, core/structs.go
Modified the Source struct by adding a new field named Checksum of type string. This field will be validated using the sha256sum algorithm, provided it exists in the Source struct. If the checksum does not match, the DownloadTarSource function will now return an error.
=> Validate checkshum for downloaded files excluding git files

.github/workflows/build.yml, .github/workflows/release.yml
- Bump `actions/setup-go` to `v5` (Node 20).
- Set the go version to 1.21.
=> feat/ci: bump actions/setup-go to v5

core/plugins.go
Stops vib from calling a plugin BuildModule twice.
closes #16
=> fix:[close #16] stop calling plugin twice

core/loader.go
This is the Containerfile using our in repo example:
```dockerfile
FROM debian:sid-slim AS build
LABEL maintainer='Vanilla OS Contributors'
ARG DEBIAN_FRONTEND=noninteractive
RUN echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
ADD includes.container /
ADD sources /sources
RUN apt-get update
RUN apt install -y  libbtrfs-dev golang-go  && apt clean && cd /sources/abroot-git && go build -o /usr/local/bin/abroot
RUN apt install -y  xterm && apt clean
RUN apt install -y  wget curl  && apt clean
RUN apt install -y  nano vim  && apt clean
RUN mv /sources/man/man1/abroot.1 /usr/share/man/man1/ && apt install -y podman golang-github-containers-common patch wget && mkdir -p /usr/bin && cp /sources/abrootv2 /usr/bin/abroot && chmod +x /usr/bin/abroot && dpkg-divert --add …
```
=> fix: included modules not being included in the final recipe

docs/website/src/examples.hbs
Currently, both the examples on the website are the same (i.e. https://vib.vanillaos.org/examples) which was brought to my notice by someone on Discord, fixed the Node application example by going through the Git commit history and porting it to the newer Vib format.
=> docs: fix incorrect Node example

core/plugins.go, core/structs.go, go.mod, go.sum
This migrates plugins from using go/plugin to ebitengine/purego and c-shared. With this change vib and plugins do not need to be built against the exact same api version anymore, which makes the deployment of vib with plugins much easier.
TODO:
This pr is part of #34
=> feat: Migrate plugins to c-shared

core/meson.go
Uses the checksum of the source and the name of the module to generate the folder name in `/tmp/` instead of using a random uuid
Closes #40
=> feat[closes #40]: Dont use random directories for tmp

core/build.go
Uses the exec format for entrypoint as defined in https://docs.docker.com/reference/dockerfile/#entrypoint
Closes #36
=> fix[closes #36]: Use exec format for entrypoint

api/structs.go, core/build.go, go.mod
Uses the exec format for `cmd` as defined in https://docs.docker.com/reference/dockerfile/#cmd
This is a breaking change for any recipe that uses the `cmd` field.
closes #37
=> feat[closes #37]: Use exec format for cmd

api/download.go, api/structs.go, core/apt.go, core/cmake.go, core/dpkg-buildpackage.go, core/dpkg.go, core/go.go, core/make.go, core/meson.go
This makes vib download any sources into a subdirectory for every module and adds the option to download files into an extra subdirectory to allow easier seperation of sources.
Closes #45
=> feat[close #45]: Add source destination option and split up sources

core/apt.go
Closes #50 
`apt` is the recommended command for interactive use by administrators, not for use in shell scripts. Furthermore, the current use of `apt` is causing CLI warnings:
>  apt does not have a stable CLI interface. Use with caution in scripts.
This PR updates the apt core package to use `apt-get *` command variants for all apt commands (install and clean) 
- Use `apt-get install` instead of `apt install`
- Use `apt-get clean` instead of `apt clean`
- Some formatting changes (via https://github.com/incu6us/goimports-reviser)
Using the following `vib.yml` recipe:
```yml
name: my-recipe
id: my-test
stages:
- id: build
base: debian:sid-slim
labels:
maintainer: My Awesome Team
args:
DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > …
```
=> feat[closes #50]: Use apt-get instead of apt

core/shell.go, plugins/apt.go
Closes #50 
Related to: https://github.com/Vanilla-OS/Vib/commit/60a7d883bd3238506d6e7b6d720995a7859156aa#r143184779
1. `apt` is the recommended command for interactive use by administrators, not for use in shell scripts. Furthermore, the current use of `apt` is causing CLI warnings:
>  apt does not have a stable CLI interface. Use with caution in scripts.
2. go build fails due to inconsistent package name
This PR updates the apt core package to use `apt-get *` command variants for all apt commands (install and clean) and fixes the incorrect package name so that the application can be successfully built.
- Use `apt-get install` instead of `apt install`
- Use `apt-get clean` instead of `apt clean`
-  Update package name to match module directory (core)
- Some formatting changes (via …
=> fix[closes #50]: Use apt-get instead of apt and fix go build

cmd/build.go
This will let the users to run `vib build` with a recipe yml file in the folder. You can still provide the recipe name in the command, that's still the recommended way.
In addition to this fix, I have also added the following validation:
1. file check to see whether the provided recipe path exists.
2. extension check for either yml or yaml.
It's best to catch errors early in **cmd** than to leave to other packages.
It is also recommended to use `errors.Is(...)` instead of `os.Is(...)`. Refer to the following golang issue
https://github.com/golang/go/issues/41122
=> fix/53 Building a container image without a recipe name throws error

api/structs.go, core/build.go, core/loader.go, core/structs.go, docs/articles/en/recipe-structure.md
Closes #38
⚠️NOTE⚠️
---
- I am marking this PR as a draft since a lot of things require feedback from the upstream developers.
- The proposed changes introduce **breaking changes** as they alter the recipe structure meaning that existing recipes will no longer build without adopting the new style.
- I will be happy to do any necessary adjustments to be in line with the upstream developers' vision of this feature.
- The workdir related checks for each supported command are the same so maybe we can extract it to avoid duplicated code. I want to avoid refactoring/simplification until we come to an agreement of how this feature should be implemented.
This PR adds support for the [`WORKDIR`](https://docs.docker.com/reference/dockerfile/#workdir) instruction to various commands.  It also checks …
=> feat[closes #38]: add workdir instruction support

api/structs.go, core/build.go, docs/articles/en/recipe-structure.md
⚠️NOTE⚠️
---
- The proposed changes introduce **breaking changes** as they alter the recipe structure meaning that existing recipes will no longer build without adopting the new style.
This PR adjusts the `COPY` command structure to be in line with the similar `ADD` command. This ensures consistency and closely emulates how raw Dockerfiles work.
- Update `Copy` structure to use a map to specify source and destination
- Remove the unecessary `Path` structure 
- Update recipe structure documentation
```yml
copy:
- workdir: /tmp
from: build
paths:
- src: /app/awesome.txt
dst: .
- src: /tmp/test.txt
dst: .
- workdir: /etc
paths:
- src: /app/hello.txt
dst: .
```
```yml
copy:
- workdir: /tmp
from: build
srcdst:
/app/awesome.txt: .
/tmp/test.txt: .
- workdir: /etc
srcdst:
/app/hello.txt: .
``` …
=> feat: copy add alignment

Makefile
Fix `make install` searching `vib` in`./` when it was actually in `build/`.
I hope the commit name suit your naming scheme.
=> fix(build): search vib bin in build/ instead of ./

core/compile.go
Makes sure that docker/podman are run with the same uid/gid as the finalize plugins, to ensure that the plugins can find the built image
=> Fix: run image build with same permissions as finalize plugins

core/compile.go, plugins/flatpak.go
Adds a flatpak plugin which allows users to automatically install flatpaks onto their system
depends on #79
=> Add a flatpak plugin

plugins/shim.go
Adds a `shim` plugin which allows users to write their own plugins in not compiled languages (such as bash or python), making it much easier to add plugins to vib
=> feat: add shim plugin

docs/articles/en/getting-started.md, example/example.yml
The "Getting Started" example seems to be missing the `commands`  instruction under the `runs` section. As discussed in https://github.com/Vanilla-OS/Vib/issues/92, the installation instructions are also outdated, but updating the example felt like a quick win already, which will probably prevet other user to dig the documentaion like I had to.
=> fix: add missing commands to example

core/shell.go
Allows users to define multiple sources in the `shell` module, this removes the existing `source` property and replaces it with the `sources` property, and therefore is a breaking change.
=> feat: allow multiple sources for shell module

plugins/meson.go
Add buildflags option to meson as described in the vib documentation.
Relates to https://github.com/Vanilla-OS/Vib/issues/107
=> feat: Add buildflags to meson plugin

docs/articles/en/built-in-modules.md
Update the docs for the meson buildargs option.  Convert example to use list
=> fix: update buildflags meson example

docs/articles/en/getting-started.md
Updates the getting started document to reflect our changes with externally built plugins.
=> Fix: update getting started to show vib plugin instructions

api/download.go, api/finalize-scopes.go, api/structs.go, cmd/build.go, cmd/compile.go, cmd/root.go, cmd/test.go, core/build.go, core/compile.go, core/finalize.go, core/resolver_test.go, core/shell.go, core/structs.go, finalize-plugins/genimage.go, finalize-plugins/shell-final.go, finalize-plugins/sysext.go, finalize-plugins/systemd-repart.go, plugins/apt.go, plugins/cmake.go, plugins/dpkg-buildpackage.go, plugins/flatpak.go, plugins/go.go, plugins/make.go, plugins/meson.go, plugins/shim.go
I do not know if this is relevant to you.
When i saw Pallas i went through the system to see how it generates the HTML sites. 
I realized it needs the comments in order to provide the small description for each function and struct.
Then i started going through Vib and added the descriptions in *core* everywhere it was missing.
If this is accepted i would go on with adding descriptions.
Let me know if this is wasted time.
Cheers.
=> chore: added Pallas compatible comments

docs/articles/en/built-in-modules.md, plugins/make.go
Adds support for custom build flags/commands in the make plugin and updates the docs in accordance.
Closes #107
=> feat: add support for extra buildflags in the make plugin

.github/workflows/vendored-release.yml
=> feat: Add workflow to release source tarball with vendored deps

api/structs.go, core/build.go, core/plugins.in, core/shell.go, core/structs.go, plugins/apt.go, plugins/cmake.go, plugins/dpkg-buildpackage.go, plugins/flatpak.go, plugins/go.go, plugins/make.go, plugins/meson.go, plugins/shim.go
Allows plugins to add their own containerfile commands instead of being forced to only include `RUN`s
Needed for #104 
this also removes the singlelayer option in vib, as it wasn't functional either way and would only make this harder to implement. It's not a breaking change, and the only vib recipe that previously used singlelayer was pico-image, but nothing about the resulting image changes without the singlelayer flag
=> Allow plugins to define custom containerfile commands

api/download.go, api/structs.go, core/build.go, plugins/apt.go, plugins/dpkg-buildpackage.go
Instead of staging sources all at once, allow vib to stage sources per module and clean sources after the module by itself, this allows users to manage sources easier and also completely skip the sources step if no module defines any sources.
closes #104
=> feat: [close #104] Stage sources per module

cmd/root.go, main.go
Exit with a nonzero return code when vib fails and dont print the usage output on error
=> fix: exit with non zero returncode on error

api/download.go, api/structs.go, core/build.go, core/loader.go, core/shell.go, plugins/cmake.go, plugins/dpkg-buildpackage.go, plugins/go.go, plugins/make.go, plugins/meson.go
This makes it easier for users to configure local includes by allowing the includes directory to be changed in the recipe and adding a source type that copies local files
=> feat: Make it easier to configure local includes

api/structs.go, core/build.go
Adds a new property `addincludes` which lets the user decide if a stage should include the `includes.container`
closes #105
=> feat [close #105]: Add property to decide wether to add includes per stage

api/download.go, finalize-plugins/systemd-repart.go, plugins/apt.go, plugins/cmake.go, plugins/make.go, plugins/meson.go
Adds support for defining more than one source in the meson and make plugins as well as some improvements in systemd-sysext
=> Feat: Allow multiple sources in plugins

docs/articles/en/built-in-modules.md, docs/articles/en/getting-started.md, docs/articles/en/github-action.md, docs/articles/en/making-plugin.md, docs/articles/en/recipe-structure.md, docs/articles/en/use-modules.md
This updates the docs to make them accurate for the upcoming 1.0.0 release
=> chore: Update docs to prepare for v1.0.0 release

cmd/root.go, core/compile.go, go.mod, go.sum
Change the order in which UID and GID are changed to properly drop all root privileges, currently the GID fails meaning the effective user ends up being a regular user with the root group
=> fix: Properly drop root privileges when run with sudo

.github/workflows/build.yml, .github/workflows/release.yml
This PR introduces cross-compilation for arm64 in GitHub Actions workflows.
Related to https://github.com/Vanilla-OS/live-iso/issues/87.
=> feat: build arm64 binary

api/arch.go, api/structs.go, cmd/build.go, cmd/compile.go, core/build.go, core/compile.go, core/plugins.in, core/shell.go, core/structs.go, plugins/apt.go, plugins/cmake.go, plugins/dpkg-buildpackage.go, plugins/go.go, plugins/make.go, plugins/meson.go
=> feat: add `only-arches` filter to source

api/download.go
Before:
```
[nisel@MiWiFi-R4A-srv core-image]$ ~/.local/bin/vib-amd64 build
Building recipe Planifolia Core
Building module [packages-modules] of type [includes]
Building module [abroot] of type [shell]
Downloading source: https://github.com/nisel11/ABRoot/releases/download/v2.2.0/abrootv2.tar.gz
Source is tar: https://github.com/nisel11/ABRoot/releases/download/v2.2.0/abrootv2.tar.gz
Moving source: abroot
Error: exit status 2
```
Now:
```
[nisel@MiWiFi-R4A-srv core-image]$ ~/dev/planifolia/Vib/build/vib-amd64 build
Building recipe Planifolia Core
Building module [packages-modules] of type [includes]
Building module [abroot] of type [shell]
Downloading source: https://github.com/nisel11/ABRoot/releases/download/v2.2.0/abrootv2.tar.gz
Source is tar: …
```
=> fix: remove "*" from moving tar sources
